Vagrant.configure("2") do |config|
  
  config.vm.define :kubemaster do |kubemaster|
  kubemaster.vm.network "private_network", ip: "192.168.100.101", virtualbox__intnet: true
  kubemaster.vm.box = "centos/7"
  kubemaster.vm.hostname = 'kubemaster'
  kubemaster.vm.synced_folder './salt-stack/salt', '/srv/salt'
  kubemaster.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  vb.cpus = 2
#  vb.customize ['modifyvm', :id, '--macaddress1', '080027000051']
#     vb.customize ['modifyvm', :id, '--natnet1', '10.0.51.0/24']
  end
  kubemaster.vm.provision :salt do |salt|
      salt.masterless = true
      salt.run_highstate = true
    end
  end 
  
  config.vm.define :kube1 do |kube1|
  kube1.vm.network "private_network", ip: "192.168.100.102", virtualbox__intnet: true
  kube1.vm.box = "centos/7"
  kube1.vm.hostname = 'kube1'
  kube1.vm.synced_folder './salt-stack/salt', '/srv/salt'
  kube1.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  vb.cpus = 2
#  vb.customize ['modifyvm', :id, '--macaddress1', '080027000052']
#	vb.customize ['modifyvm', :id, '--natnet1', '10.0.52.0/24']
  end
  kube1.vm.provision :salt do |salt|
      salt.masterless = true
      salt.run_highstate = true
    end
  end 
  
  config.vm.define :kube2 do |kube2|
  kube2.vm.network "private_network", ip: "192.168.100.103", virtualbox__intnet: true
  kube2.vm.box = "centos/7"
  kube2.vm.hostname = 'kube2'
  kube2.vm.synced_folder './salt-stack/salt', '/srv/salt'
  kube2.vm.provider "virtualbox" do |vb|
  vb.memory = "2048"
  vb.cpus = 2
 # vb.customize ['modifyvm', :id, '--macaddress1', '080027000053']
#	vb.customize ['modifyvm', :id, '--natnet1', '10.0.53.0/24']
  end
  kube2.vm.provision :salt do |salt|
      salt.masterless = true
      salt.run_highstate = true
    end
  end

end
